<a href="https://colab.research.google.com/github/ANJALICHAMOLI/PyTorch/blob/main/1_tensors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# creating tensor using empty
a = torch.empty(2,3)
print(a)
#empty function creates a memory of the tensor assigned
#and gets the value at that tensor in the memory
#no new memory is assigned the already assgined memory is shown

tensor([[1.9462e+23, 4.3240e-41, 1.9194e+22],
        [4.3240e-41, 1.2135e+20, 4.3240e-41]])


In [ ]:
# checking type of tensor
type(a)

torch.Tensor

In [ ]:
# making a tensor with all values assigned with 0 using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# making a tensor with all values assgined as 1 using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand to give random values for initalized tensor
torch.rand(2,3)

tensor([[0.8516, 0.9045, 0.6017],
        [0.5142, 0.3682, 0.6549]])

In [ ]:
# using random (rand)intializes random values everytime hence we use seed to maintain the consistency for every run
# (reporoduceablity)

In [ ]:
# hence manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor we can make custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways to create tensors

# arange-> can define a range
print("using arange ->", torch.arange(0,10,2))

# using linspace (linearly spread values for a given range (evenly spread))
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# creating a tensor exaclty like another tensor
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3761175520770024294]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# rand genrates flaot values so when we say make a tensor like 'x'
# which has integer values it leads to error hence we have to explicitly tell
# it to make it
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6964, 0.9227, 0.3545],
        [0.4945, 0.3143, 0.6103]])

## Tensor Data Types

In [ ]:
# finding data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.2,2.9,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to() to change one data type to another
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.3776, 0.9525],
        [0.7244, 0.6258]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.1426, 0.9073],
        [0.5247, 0.3916]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8867, 0.4265, 0.5541],
        [0.9513, 0.6130, 0.3810]])
tensor([[0.4535, 0.5934, 0.8606],
        [0.6858, 0.8637, 0.5527]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0554, 0.1872, 0.3761],
        [0.0008, 0.5572, 0.0091]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp ( keeps nos in a range)
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 8., 7.],
        [5., 4., 5.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18, 13])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6., 6., 6.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(4.)

In [ ]:
# product
torch.prod(e)

tensor(39200.)

In [ ]:
# standard deviation
torch.std(e)

tensor(1.5492)

In [ ]:
# variance
torch.var(e)

tensor(2.4000)

In [ ]:
# argmax (biggest item position)
torch.argmax(e)

tensor(1)

In [ ]:
# argmin (smallest item position)
torch.argmin(e)

tensor(4)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 7, 0],
        [6, 9, 5]])
tensor([[0, 0],
        [0, 6],
        [5, 2]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 0, 42],
        [25, 64]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 6],
        [7, 9],
        [0, 5]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 6., 7.],
        [4., 3., 3.],
        [2., 4., 6.]])

In [ ]:
# determinant
torch.det(h)

tensor(-32.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1875,  0.2500,  0.0938],
        [ 0.5625,  0.2500, -0.7812],
        [-0.3125, -0.2500,  0.6562]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 1, 8],
        [8, 5, 9]])
tensor([[7, 4, 4],
        [2, 6, 3]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[ True,  True, False],
        [False,  True, False]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 2., 0.],
        [0., 1., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 0.6931,   -inf],
        [  -inf, 0.0000, 0.6931]])

In [ ]:
# exp
torch.exp(k)

tensor([[148.4132,   7.3891,   1.0000],
        [  1.0000,   2.7183,   7.3891]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 1.4142, 0.0000],
        [0.0000, 1.0000, 1.4142]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.8808, 0.5000],
        [0.5000, 0.7311, 0.8808]])

In [ ]:
# softmax
torch.softmax(k, dim=0) #0,-1=columns,1=rows

tensor([[0.9933, 0.7311, 0.1192],
        [0.0067, 0.2689, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 2., 0.],
        [0., 1., 2.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1830, 0.3563, 0.9836],
        [0.5694, 0.9776, 0.1624]])
tensor([[0.9059, 0.1838, 0.4992],
        [0.2424, 0.2673, 0.0924]])


In [ ]:
# adding matrix normally m+n specifies memory seprately  for the calcuation
# but we might want changes to be storewd in one of the matrix instead
m.add_(n)# hence this add function (the changes are in m)

tensor([[1.9948, 0.7240, 1.9820],
        [1.0541, 1.5122, 0.3471]])

In [ ]:
m

tensor([[1.9948, 0.7240, 1.9820],
        [1.0541, 1.5122, 0.3471]])

In [ ]:
n

tensor([[0.9059, 0.1838, 0.4992],
        [0.2424, 0.2673, 0.0924]])

In [ ]:
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m.relu_()

tensor([[1.9948, 0.7240, 1.9820],
        [1.0541, 1.5122, 0.3471]])

In [ ]:
m

tensor([[1.9948, 0.7240, 1.9820],
        [1.0541, 1.5122, 0.3471]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5403, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
b = a
#copy is created but changes in a will be the changes in b too

In [ ]:
b

tensor([[0.5403, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
b

tensor([[0.0000, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
b = a.clone() #hence we use clone fun to copy

In [ ]:
a

tensor([[0.0000, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
b

tensor([[0.0000, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.2063,  0.0147],
        [ 0.6687,  0.8886,  0.1386]])

In [ ]:
b

tensor([[0.0000, 0.2063, 0.0147],
        [0.6687, 0.8886, 0.1386]])

# Tensor operation on gpu

In [ ]:
torch.cuda.is_available()#checking if have gpu in env

True

In [ ]:
device = torch.device('cuda') #stroing device

In [ ]:
#creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.2809, 0.1030, 0.1689],
        [0.9691, 0.9894, 0.6035]], device='cuda:0')

In [ ]:
a=torch.rand(2,3) #on cpu
a

tensor([[0.2833, 0.3938, 0.8990],
        [0.2465, 0.3482, 0.8867]])

In [ ]:
# moving existing cpu tensor to gpu
b=a.to(device)

In [ ]:
# comapring tensor in cpu and gpu
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Creating random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time =time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

# Print GPU performance result
print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 15.7953 seconds
Time on GPU: 0.5919 seconds


In [ ]:
#hence clearly gpu wins  and should be sued to safe time as it has more gain over cpu

# Reshaping tensors

In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b= torch.rand(2,3,4)
b

tensor([[[0.8830, 0.5769, 0.9372, 0.8037],
         [0.3910, 0.1387, 0.6050, 0.7768],
         [0.4135, 0.8577, 0.0421, 0.8891]],

        [[0.4703, 0.5202, 0.4997, 0.0341],
         [0.4129, 0.8433, 0.9368, 0.9169],
         [0.8579, 0.5188, 0.8371, 0.7963]]])

In [ ]:
#permute changes the oder acc to pos mentioned
b.permute(2,0,1) #2 pos dim in older tensor = new 1st pos

tensor([[[0.8830, 0.3910, 0.4135],
         [0.4703, 0.4129, 0.8579]],

        [[0.5769, 0.1387, 0.8577],
         [0.5202, 0.8433, 0.5188]],

        [[0.9372, 0.6050, 0.0421],
         [0.4997, 0.9368, 0.8371]],

        [[0.8037, 0.7768, 0.8891],
         [0.0341, 0.9169, 0.7963]]])

In [ ]:
#unsqueeze
c=torch.rand(256,256,3)
c.unsqueeze(0).shape

torch.Size([1, 256, 256, 3])

In [ ]:
# squeeze
d=torch.rand(1,40)
d.squeeze(0).shape

torch.Size([40])

# Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy() #converting to numpy
b

array([1, 2, 3])

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)#converts from numpy to tensor

tensor([1, 2, 3])