<a href="https://colab.research.google.com/github/ANJALICHAMOLI/PyTorch/blob/main/6_dataset_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# dataloader and dataset are abstractions in pytorch that
# decouple the process of defining data and itrating over
# it in training loops

In [ ]:
# dataset class - loads data from memoery
#                 knows where data is stored in memory
#                  loads data row by row from memory
# dataloader class - decides the batches in data
#                   makes batches

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0] #no of rows in data

  def __getitem__(self, index): #getting the indexed row

    return self.features[index], self.labels[index]

In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[9] #row data

(tensor([-0.5872, -1.9717]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


In [ ]:
# sampler - this suffling of rows intially (idex) is done by sampler
# -it determines the strategy to sample rows from dataset during data laoding
# -controls how indices of the dataset are drwan for each batch

# types :-
# sequential smapler -> shuffle = False
# random sanpler -> shuffle = True

In [ ]:
# collate_fn
# this function in pytorch datalaoder is a fun that specifies how to combine the list of samples from a dataset into a single batch
# the datalaoder by default uses a simple batch collation machanism

In [ ]:
#these calssses along with these paremters it provides help implememnt alot like:-

# Mini-Batch Gradient Descent: Instead of loading the entire dataset into memory (which is memory-inefficient), the DataLoader divides data
# into smaller chunks or "batches," allowing for more frequent parameter updates and faster convergence .

# Data Transformations: can easily integrate preprocessing steps such as resizing images, converting them to grayscale, or textual
#  augmentation directly within the __getitem__ method of Dataset class manipulate how many rows of data to keep andhow many to drop

#  Shuffling and Sampling: The DataLoader automatically manages the randomization of data access using Samplers. By setting shuffle=True,
# it reshuffles the indices at the start of each epoch to prevent the model from learning the order of the data

# Parallelization: To speed up the training process, the DataLoader supports multi process data loading via the num_workers parameter. This allows
#  multiple workers to fetch and transform data chunks in parallel while the model is training .

#  Batch Management & Collation: The DataLoader uses a collate function to specify how individual samples (rows) fetched by the Dataset should be combined
#  or "collated" into a single batch tensor, which is especially useful when you need to handle variable length data (like padding text) .

# Flexible Control: Through parameters like drop_last, granular control over whether to discard an incomplete final batch if the dataset size
# isn't perfectly divisible by batch size is possible.
